/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veritabani2o;

import events.izin;
import events.izinController;
import events.kController;
import events.kullanici;
import events.yController;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author a
 */
public class yoneticiG extends javax.swing.JFrame {

    /**
     * Creates new form yoneticiG
     */
    public yoneticiG() throws SQLException {
        initComponents();
        kulGos();
        kullaniciDoldur();
        araKul();
        izinListele();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField11 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yönetim Paneli");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("asd");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        jTextField5.setText("jTextField5");

        jTextField6.setText("jTextField6");

        jTextField7.setText("jTextField7");

        jTextField8.setText("jTextField8");

        jLabel1.setText("Ad");

        jLabel2.setText("Soyad");

        jLabel3.setText("Tc No");

        jLabel4.setText("Sicil No");

        jLabel5.setText("Cinsiyet");

        jLabel6.setText("Doğum Tarihi");

        jLabel7.setText("Şehir");

        jLabel8.setText("Birim");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Bütün Kullanıcılar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ad", "Soyad", "Tc No", "Sicil No", "Cinsiyet", "Doğum Tarihi", "Şehir", "Birim"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Yöneticinin Bilgileri");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jTextField3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField6)
                            .addComponent(jTextField5)
                            .addComponent(jTextField7)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(68, 68, 68)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kişisel Bilgiler", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ad", "Soyad", "Tc No", "Sicil No", "Cinsiyet", "Doğum Tarihi", "Şehir", "Birim"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kayıt No","Başlangıç", "Bitiş", "Kullanılan Miktar", "İzin Türü", "Kabul"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Kullanıcılar");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("İzinler");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ad", "Soyad", "Sicil NO" }));

        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField9KeyReleased(evt);
            }
        });

        jButton1.setText("Ara");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Aramak İstediğiniz Kriter");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hepsi", "Yıllık", "Mazeret", "Rapor","Ücretsiz" }));

        jButton2.setText("Ara");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setText("İzin Türü");

        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField10KeyReleased(evt);
            }
        });

        jLabel15.setText("Sicil No");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hepsi", "Yillik", "Mazeret", "Rapor","Ücretsiz" }));

        jCheckBox1.setText("Kabul Edildi");

        jTextField11.setText("Kayıt No");

        jButton3.setText("Kaydet");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel16.setText("Kabul etmek veya reddetmek istediğiniz izinin kayıt numarasıyla aşağıdan yapınız");

        jLabel17.setText("İzinlerini görmek istediğiniz kullanıcının sicil numarasını aşağıdan girip izinlerini görebilirsiniz.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(98, 98, 98))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel16)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)))
                        .addGap(155, 155, 155)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kullanıcı Arama işlemleri ve İzin Bilgileri", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        giris g = new giris();
        g.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox3.getSelectedItem().toString().equals("Hepsi"))
        {
            if(jComboBox1.getSelectedItem().toString().equals("Ad"))
            {
                araKulDoldur("Ad"," like '"+jTextField9.getText()+"%' and i.kullanici_id = g.kullanici_id");
            }
            else if(jComboBox1.getSelectedItem().toString().equals("Soyad"))
            {
                araKulDoldur("Soyad"," like '"+jTextField9.getText()+"%' and i.kullanici_id = g.kullanici_id");
            }
            else if(jComboBox1.getSelectedItem().toString().equals("Sicil NO"))
            {
                araKulDoldur("Sicil_No"," = "+jTextField9.getText()+" and i.kullanici_id = g.kullanici_id");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Yanlış "+jComboBox1.getSelectedItem().toString(), "Hata", WIDTH);
            }
        }
        else
        {
            if(jComboBox1.getSelectedItem().toString().equals("Ad"))
            {
                araKulDoldur("g.Ad"," like '"+jTextField9.getText()+"%' and i.izin_Tur = '"+jComboBox3.getSelectedItem().toString()+"' and i.kullanici_id = g.kullanici_id");
            }
            else if(jComboBox1.getSelectedItem().toString().equals("Soyad"))
            {
                araKulDoldur("g.Soyad"," like '"+jTextField9.getText()+"%' and i.izin_Tur = '"+jComboBox3.getSelectedItem().toString()+"' and i.kullanici_id = g.kullanici_id");
            }
            else if(jComboBox1.getSelectedItem().toString().equals("Sicil NO"))
            {
                araKulDoldur("g.Sicil_No"," = "+jTextField9.getText()+" and i.izin_Tur = '"+jComboBox3.getSelectedItem().toString()+"' and i.kullanici_id = g.kullanici_id");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyReleased
        // TODO add your handling code here:
        if(jComboBox3.getSelectedItem().toString().equals("Hepsi"))
        {
            if(jComboBox1.getSelectedItem().toString().equals("Ad"))
            {
                araKulDoldur("Ad"," like '"+jTextField9.getText()+"%' and i.kullanici_id = g.kullanici_id");
            }
            else if(jComboBox1.getSelectedItem().toString().equals("Soyad"))
            {
                araKulDoldur("Soyad"," like '"+jTextField9.getText()+"%' and i.kullanici_id = g.kullanici_id");
            }
            else if(jComboBox1.getSelectedItem().toString().equals("Sicil NO"))
            {
                araKulDoldur("Sicil_No"," = "+jTextField9.getText()+" and i.kullanici_id = g.kullanici_id");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Yanlış "+jComboBox1.getSelectedItem().toString(), "Hata", WIDTH);
            }
        }
        else
        {
            if(jComboBox1.getSelectedItem().toString().equals("Ad"))
            {
                araKulDoldur("g.Ad"," like '"+jTextField9.getText()+"%' and i.izin_Tur = '"+jComboBox3.getSelectedItem().toString()+"' and i.kullanici_id = g.kullanici_id");
            }
            else if(jComboBox1.getSelectedItem().toString().equals("Soyad"))
            {
                araKulDoldur("g.Soyad"," like '"+jTextField9.getText()+"%' and i.izin_Tur = '"+jComboBox3.getSelectedItem().toString()+"' and i.kullanici_id = g.kullanici_id");
            }
            else if(jComboBox1.getSelectedItem().toString().equals("Sicil NO"))
            {
                araKulDoldur("g.Sicil_No"," = "+jTextField9.getText()+" and i.izin_Tur = '"+jComboBox3.getSelectedItem().toString()+"' and i.kullanici_id = g.kullanici_id");
            }
        }
    }//GEN-LAST:event_jTextField9KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jTextField10.getText().equals(""))
        {
            izinListele();
        }
        else
        {
            izinAra();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try
        {
            if(Integer.parseInt(jTextField11.getText()) < 999999999 && Integer.parseInt(jTextField11.getText()) > -999999999)
            {
                if(JOptionPane.showConfirmDialog(this, jTextField11.getText()+" kayıt numaralı izini güncellemek istediğinizden emin misiniz ?","",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
                {
                    if(jCheckBox1.isSelected())
                    {
                        izinController ic = new izinController();
                        ic.izinOnay(jTextField11.getText(), "1");
                    }
                    else
                    {
                        izinController ic = new izinController();
                        ic.izinOnay(jTextField11.getText(), "0");
                    }
                    jButton2ActionPerformed(evt);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Yanlış bir kayıt numarası girdiniz lütfen kontrol ediniz!","Dikkat",WIDTH);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Yanlış bir kayıt numarası girdiniz lütfen kontrol ediniz!","Dikkat",WIDTH);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField10KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yoneticiG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yoneticiG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yoneticiG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yoneticiG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new yoneticiG().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(yoneticiG.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    void kulGos() throws SQLException
    {
        try
        {
            kController kc = new kController();
            yController yc = new yController();
            kullanici kul = new kullanici();
            kul = yc.kulcek(kc.sonGiris());
            jTextField1.setText(kul.getAd());
            jTextField2.setText(kul.getSoyad());
            jTextField3.setText(kul.getTc());
            jTextField4.setText(kul.getSicil());
            jTextField5.setText(kul.getCinsiyet());
            jTextField6.setText(kul.getDogt());
            jTextField7.setText(kul.getSehir());
            jTextField8.setText(kul.getBirim());
        }
        catch(Exception e)
        {
            System.out.print(e.getMessage());
        }
        
    }
    void kullaniciDoldur()
    {
        kController kc =new kController();
        yController yc = new yController();
        List<kullanici> mlist=null;
        DefaultTableModel mustablo = (DefaultTableModel) jTable1.getModel();
        
        mustablo.getDataVector().clear();
        jTable1.repaint();
        
        mlist = yc.kulDoldur();
        Vector[] v = new Vector[mlist.size()];
        for(int i=0;i<mlist.size();i++){
            v[i] = new Vector();
            v[i].add(mlist.get(i).getAd());
            v[i].add(mlist.get(i).getSoyad());
            v[i].add(mlist.get(i).getTc());
            v[i].add(mlist.get(i).getSicil());
            v[i].add(mlist.get(i).getCinsiyet());
            v[i].add(mlist.get(i).getDogt());
            v[i].add(mlist.get(i).getSehir());
            v[i].add(mlist.get(i).getBirim());
            mustablo.insertRow(i, v[i]);
        }
    }
    void araKul()
    {
        kController kc =new kController();
        yController yc = new yController();
        List<kullanici> mlist=null;
        DefaultTableModel mustablo = (DefaultTableModel) jTable2.getModel();
        mustablo.getDataVector().clear();
        jTable1.repaint();
        
        mlist = yc.kulDoldur();
        Vector[] v = new Vector[mlist.size()];
        for(int i=0;i<mlist.size();i++){
            v[i] = new Vector();
            v[i].add(mlist.get(i).getAd());
            v[i].add(mlist.get(i).getSoyad());
            v[i].add(mlist.get(i).getTc());
            v[i].add(mlist.get(i).getSicil());
            v[i].add(mlist.get(i).getCinsiyet());
            v[i].add(mlist.get(i).getDogt());
            v[i].add(mlist.get(i).getSehir());
            v[i].add(mlist.get(i).getBirim());
            mustablo.insertRow(i, v[i]);
        }
    }
    void araKulDoldur(String bir,String iki)
    {
        kController kc =new kController();
        yController yc = new yController();
        List<kullanici> mlist=null;
        DefaultTableModel mustablo = (DefaultTableModel) jTable2.getModel();
        mustablo.getDataVector().clear();
        jTable1.repaint();
        
        mlist = yc.kulAraDoldur("select g.* from giris g,izinler i where "+bir+iki);
        Vector[] v = new Vector[mlist.size()];
        for(int i=0;i<mlist.size();i++){
            v[i] = new Vector();
            v[i].add(mlist.get(i).getAd());
            v[i].add(mlist.get(i).getSoyad());
            v[i].add(mlist.get(i).getTc());
            v[i].add(mlist.get(i).getSicil());
            v[i].add(mlist.get(i).getCinsiyet());
            v[i].add(mlist.get(i).getDogt());
            v[i].add(mlist.get(i).getSehir());
            v[i].add(mlist.get(i).getBirim());
            mustablo.insertRow(i, v[i]);
        }
    }
    void izinListele()
    {
        kController kc =new kController();
        List<izin> mlist=null;
        DefaultTableModel mustablo = (DefaultTableModel) jTable3.getModel();
        mustablo.getDataVector().clear();
        jTable1.repaint();
        
        mlist = new izinController().izinler();
        Vector[] v = new Vector[mlist.size()];
        for(int i=0;i<mlist.size();i++){
            v[i] = new Vector();
            v[i].add(mlist.get(i).getKayitno());
            v[i].add(mlist.get(i).getBaslangic());
            v[i].add(mlist.get(i).getBitis());
            v[i].add(mlist.get(i).getTur());
            v[i].add(mlist.get(i).getMiktar());
            v[i].add(mlist.get(i).getKabul());
            mustablo.insertRow(i, v[i]);
        }
    }
    void izinAra()
    {
        
        List<izin> mlist=null;
        DefaultTableModel mustablo = (DefaultTableModel) jTable3.getModel();
        mustablo.getDataVector().clear();
        jTable1.repaint();
        if(jComboBox2.getSelectedItem().toString().equals("Hepsi"))
        {
            mlist = new izinController().izinArar(jTextField10.getText(),"");
        }
        else
        {
            mlist = new izinController().izinArar(jTextField10.getText()," and izin_Tur = '"+jComboBox2.getSelectedItem().toString()+"'");
        }
        
        Vector[] v = new Vector[mlist.size()];
        for(int i=0;i<mlist.size();i++){
            v[i] = new Vector();
            v[i].add(mlist.get(i).getKayitno());
            v[i].add(mlist.get(i).getBaslangic());
            v[i].add(mlist.get(i).getBitis());
            v[i].add(mlist.get(i).getTur());
            v[i].add(mlist.get(i).getMiktar());
            v[i].add(mlist.get(i).getKabul());
            mustablo.insertRow(i, v[i]);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
